### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by jswhisperer** [letstri/vaxee#1]
Just wanted to give a shout out, this looks like in the spirit of Vue1 / angular1 and KISS principals really really nice simple DX.
I'm a fan of Pinia too but I'm going to give this a go my next project.

Cheers!

**Comment by letstri** [comment]
Thanks! I really appreciate your feedback ❤️

**Comment by jswhisperer** [comment]
I know what it's like to do awesome work and not hear enough praise just wanted to reach out and say your work is appreciated! I'm sure it will trend soon. Cheers mate.
