### ISSUE TITLE
Mismatch between Getting Started Usage and StackBlitz Sample Code

### ISSUE THREAD

**Issue by itoao** [letstri/vaxee#2]
## Description
I have noticed that there is a discrepancy between the sample code in the [Usage](https://vaxee.letstri.dev/getting-started.html#usage) section of the Getting Started documentation and the example provided in [StackBlitz](https://stackblitz.com/edit/vaxee-counter-playground?file=src%2Fstores%2Fcounter.ts,src%2FApp.vue&terminal=dev). The implementation details differ, which may lead to confusion for users trying to follow the documentation.
Specifically, the counter store implementation in the documentation does not match the one in the StackBlitz example. This inconsistency should be addressed to ensure that users have a clear and accurate reference for using the Vaxee library.

## Suggested Action
Update the Usage section in the Getting Started documentation to align with the StackBlitz example, ensuring that the code is consistent and easy to understand.

If there are no issues with this suggested action, I would like to take on this task.

**Comment by letstri** [comment]
Hello. Thank you for the issue, I've fixed the StackBlitz example.
