### ISSUE TITLE
[Feature Request] Plugin Support

### ISSUE THREAD

**Issue by mubaidr** [letstri/vaxee#3]
Hey, first of all, thanks for all the hard work on this library—looks very clean usage! I was wondering if you'd consider adding plugin support to make it easier to extend functionality. Do you think it's worth pursuing?

If so, I'd be happy to contribute with a PR. Let me know what you think!

Thanks again!

**Comment by letstri** [comment]
Hello. Thank you for the kind words, I'm really glad you liked Vaxee!

I also thought about plugin functionality, but I couldn't come up with use cases where plugins would actually be useful. What ideas do you have for plugins?

**Comment by mubaidr** [comment]
For now, the only usage I have in mind is a plugin capable of `persistent` storage. By using local storage/ chrome storage (yeah, I do develop chrome extensions a lot). 

But we have to decide if this is worth the effort to introduce whole new plugin functionality. Or we leave it user to use custom composable for this kind of usage.

**Comment by letstri** [comment]
I see. My goal with Vaxee is to provide as much as I can without any plugins, etc., to simplify DX. Also, Vaxee already has persistence: https://vaxee.letstri.dev/state.html#persist.

If you want to help improve Vaxee, you can contribute by adding functionality directly to the `vaxee` package, as I did with the `query` function or `persist` in `state`.

p.s. Vaxee still doesn't support HMR 😅

**Comment by mubaidr** [comment]
Cool. You are right, for just single plugin, adding a whole plugin system might be pointless. 

I did not notice that `Vaxee` does not support HRM as of now! Definitely a priority.
